### ISSUE TITLE
Why was this created as a provider rather than a module?

### ISSUE THREAD

**Issue by kevcube** [idealo/terraform-provider-controltower#52]
It doesn't seem that this provider actually allows access to any control tower APIs, because there is no control tower API.

So this provider seems to replicate functionality that is within the AWS Terraform Provider - provisioning/deleting Service Catalog products.

I am wondering why this was created as an entire provider, and not just a Terraform Module wrapping Service Catalog Provisioning. Am I missing something about the functionality this provides?

**Comment by mKeRix** [comment]
Correct, there are no direct Control Tower APIs yet. The provider was mainly created to work around the oddities of how Control Tower Account Provisioning works. The main additional features, which could not be provided in a module, are:

- limiting provisioning to a single account at a time (otherwise Control Tower will error out)
- setting tags on the managed account in AWS Organizations
- providing account data as outputs (e.g. account id)

In the end, you can achieve account provisioning using native resources in current versions of the Terraform AWS Provider, however it will be a bit more fragile than the implementation here.

Closing the issue as the main question has been answered, but feel free to hit us with any follow up questions!
